### ISSUE TITLE
`executeProposal` failure for multi-tx proposal

### ISSUE THREAD

**Issue by buckie** [gnosis/zodiac-module-reality#22]
Here's the pull you requested @rmeissner, let me know what else is needed. In the meantime I'll try another proposal that does a single tx vs a multi.

Failing to execute proposal:
```
$ cat bridge_proposal_3.json
{
    "id": "irFNzGV0BPfAdAA4lH68mLuZXHgJ4_wJADsMPTw2PtM",
    "txs": [
        {
            "to": "0x9AD2Bc9435D41Cc6f55a681552071C2EabDB2b31",
            "value": "1",
            "data": "0x",
            "operation": 0
        },
        {
            "to": "0x140E42Ff76591Bf20675952Cc1B15774F75707c0",
            "value": "2",
            "data": "0x",
            "operation": 0
        }
    ]
}
```

Etherescan says the tx [succeeded](https://rinkeby.etherscan.io/tx/0xed4742f4e3074ba0243af1b240f2e352bc294cb54cc69a0aa4eb388db37232e3) but my account balances are unchanged and the CLI says it failed.

```
$ /Users/wjm/repos/dao-module/node_modules/.bin/hardhat --network rinkeby executeProposal --module 0xD0A9A4cd312E046642341b70221358095C9c0cCE --proposal-file bridge_proposal_3.json
Transaction: 0xed4742f4e3074ba0243af1b240f2e352bc294cb54cc69a0aa4eb388db37232e3
An unexpected error occurred:

Error: cannot estimate gas; transaction may fail or may require manual gas limit (error={"name":"ProviderError","code":3,"data":"0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002550726576696f7573207472616e73616374696f6e206e6f7420657865637574656420796574000000000000000000000000000000000000000000000000000000"}, method="estimateGas", transaction={"from":"0x140E42Ff76591Bf20675952Cc1B15774F75707c0","to":"0xD0A9A4cd312E046642341b70221358095C9c0cCE","data":"0x14604b8c00000000000000000000000000000000000000000000000000000000000000e00000000000000000000000000000000000000000000000000000000000000140000000000000000000000000140e42ff76591bf20675952cc1b15774f75707c0000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000001a000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000002b6972464e7a47563042506641644141346c4836386d4c755a5848674a345f774a4144734d5054773250744d00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000026e1ce05a50d11be25515bc4b7e62d4ad5022af39bda9f325bcae16c15200c857f0a7086b4ffaf456a6af8e948c704399b2e291609c3cd4830038d00d829cfd380000000000000000000000000000000000000000000000000000000000000000"}, code=UNPREDICTABLE_GAS_LIMIT, version=providers/5.0.23)
```

If SAFE/DAO/etc addresses are needed:
```
$ cat details.rinkeby
SAFE_ADDRESS='0x842f93D83095f1cF09e8C8dd87a69A8DB3d47cdF'
DAO_ADDRESS='0x842f93D83095f1cF09e8C8dd87a69A8DB3d47cdF'
TEMPLATE_ID='0x000000000000000000000000000000000000000000000000000000000000003a'
ORACLE_ADDRESS='0x3D00D77ee771405628a4bA4913175EcC095538da'
MODULE_ADDRESS='0xD0A9A4cd312E046642341b70221358095C9c0cCE'
```

**Comment by buckie** [comment]
`executeProposal` also fails if the tx is for a single transfer.

```
$ /Users/wjm/repos/dao-module/node_modules/.bin/hardhat --network rinkeby showProposal --module 0xD0A9A4cd312E046642341b70221358095C9c0cCE --proposal-file bridge_proposal_5.json
(node:8942) Warning: Accessing non-existent property 'VERSION' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
### Proposal ####
ID: dTfqDWqYgMZHG94gnwfF2Un2Ho4lT4kepoiqQ-VGTeo
Transactions hashes hash: 0x5e210cba9848b72ea4694a4a83fdafb71d1482c6b936200f6e22ca9d217cca60
Transactions hashes: [
  '0x84f795702f4bb108e87b5ed62302404a78f78e1c6ff25a9ce59c2d227e58877c'
]
Transactions: [
  {
    to: '0x9AD2Bc9435D41Cc6f55a681552071C2EabDB2b31',
    value: '2',
    data: '0x',
    operation: 0
  }
]

$ /Users/wjm/repos/dao-module/node_modules/.bin/hardhat --network rinkeby addProposal --module 0xD0A9A4cd312E046642341b70221358095C9c0cCE --proposal-file bridge_proposal_5.json
(node:8953) Warning: Accessing non-existent property 'VERSION' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
Transaction: 0xdedf4fa091daf4714a6428cbe3f3d283be682971be9bfecb0092332a274975e5

$ /Users/wjm/repos/dao-module/node_modules/.bin/hardhat --network rinkeby executeProposal --module 0xD0A9A4cd312E046642341b70221358095C9c0cCE --proposal-file bridge_proposal_5.json
(node:9115) Warning: Accessing non-existent property 'VERSION' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
An unexpected error occurred:

Error: cannot estimate gas; transaction may fail or may require manual gas limit (error={"name":"ProviderError","code":3,"data":"0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000001c5761697420666f72206164646974696f6e616c20636f6f6c646f776e00000000"}, method="estimateGas", transaction={"from":"0x140E42Ff76591Bf20675952Cc1B15774F75707c0","to":"0xD0A9A4cd312E046642341b70221358095C9c0cCE","data":"0x14604b8c00000000000000000000000000000000000000000000000000000000000000e000000000000000000000000000000000000000000000000000000000000001400000000000000000000000009ad2bc9435d41cc6f55a681552071c2eabdb2b310000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000018000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002b6454667144577159674d5a48473934676e77664632556e32486f346c54346b65706f6971512d564754656f000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000184f795702f4bb108e87b5ed62302404a78f78e1c6ff25a9ce59c2d227e58877c0000000000000000000000000000000000000000000000000000000000000000"}, code=UNPREDICTABLE_GAS_LIMIT, version=providers/5.0.23)
```

**Comment by rmeissner** [comment]
So the tx from the comment failed because the cooldown was not yet done. (You can see the error message in the return value). I will improve the task to return the on-chain errors (should be more descriptive) and to wait for the appropriate time :).

**Comment by buckie** [comment]
Got it. Proposal 5 failed because of the cooldown timer. Sorry about that... do you have a doc/recommendation for how to extract the error message from the return value?

Unfortunately, Proposal 3 (the original example) has 2 txs and only the first one ran/executed and the second failed. To confirm this behavior,  I ran:
* `proposal_6` which is a single-tx -> success
* `proposal_7` which does a transfer to `0x9ad` then `0x140` -> only did the transfer to `0x9ad` succeded
* `proposal_8` which does a transfer to `0x140` then `0x9ad` -> only did the transfer to `0x140` succeded

## `proposal_6`
https://rinkeby.etherscan.io/tx/0x5444225e4899dbf5a79b6bf16c3053bf302d22c49d558a6daace554e62f58607#internal

## `proposal_7`
```
$ /Users/wjm/repos/dao-module/node_modules/.bin/hardhat --network rinkeby showProposal --module 0xD0A9A4cd312E046642341b70221358095C9c0cCE --proposal-file bridge_proposal_7.json
### Proposal ####
ID: jxWP5gfvOZf2DNtgsuDZOarm5S7r6KWbwRUGdV43gXs
Transactions hashes hash: 0x3df266d5bb697e2bc15b0b3ef5a181ef890e22391d1aba1381c5170bb267cdff
Transactions hashes: [
  '0x9205dd2c5d9898f9a6c4c594fa5aa32c5931f9735207f9dcfaf6809bfd7e829b',
  '0x8196fff0c5cb9ec78aaf5049f82b6dc7c127e9c53a5629a53ff79f2de60ebb83'
]
Transactions: [
  {
    to: '0x9AD2Bc9435D41Cc6f55a681552071C2EabDB2b31',
    value: '92',
    data: '0x',
    operation: 0
  },
  {
    to: '0x140E42Ff76591Bf20675952Cc1B15774F75707c0',
    value: '140',
    data: '0x',
    operation: 0
  }
]

$ /Users/wjm/repos/dao-module/node_modules/.bin/hardhat --network rinkeby addProposal --module 0xD0A9A4cd312E046642341b70221358095C9c0cCE --proposal-file bridge_proposal_7.json
Transaction: 0xf46219840d53737af2b73a38dd15fd07854e93ebaeb90c9040d16b06b930dcd1
✨  Done in 7.18s.

$ /Users/wjm/repos/dao-module/node_modules/.bin/hardhat --network rinkeby executeProposal --module 0xD0A9A4cd312E046642341b70221358095C9c0cCE --proposal-file bridge_proposal_7.json
Transaction: 0xda824dacf7c954d1225447d416d3a481df118ae6277c40ab568d2ea7ef7fbff6
An unexpected error occurred:

Error: cannot estimate gas; transaction may fail or may require manual gas limit (error={"name":"ProviderError","code":3,"data":"0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002550726576696f7573207472616e73616374696f6e206e6f7420657865637574656420796574000000000000000000000000000000000000000000000000000000"}, method="estimateGas", transaction={"from":"0x140E42Ff76591Bf20675952Cc1B15774F75707c0","to":"0xD0A9A4cd312E046642341b70221358095C9c0cCE","data":"0x14604b8c00000000000000000000000000000000000000000000000000000000000000e00000000000000000000000000000000000000000000000000000000000000140000000000000000000000000140e42ff76591bf20675952cc1b15774f75707c0000000000000000000000000000000000000000000000000000000000000008c00000000000000000000000000000000000000000000000000000000000001a000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000002b6a785750356766764f5a6632444e74677375445a4f61726d35533772364b5762775255476456343367587300000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000029205dd2c5d9898f9a6c4c594fa5aa32c5931f9735207f9dcfaf6809bfd7e829b8196fff0c5cb9ec78aaf5049f82b6dc7c127e9c53a5629a53ff79f2de60ebb830000000000000000000000000000000000000000000000000000000000000000"}, code=UNPREDICTABLE_GAS_LIMIT, version=providers/5.0.23)
    at Logger.makeError (/Users/wjm/repos/dao-module/node_modules/@ethersproject/logger/src.ts/index.ts:205:28)
    at Logger.throwError (/Users/wjm/repos/dao-module/node_modules/@ethersproject/logger/src.ts/index.ts:217:20)
    at checkError (/Users/wjm/repos/dao-module/node_modules/@ethersproject/providers/src.ts/json-rpc-provider.ts:68:16)
    at EthersProviderWrapper.<anonymous> (/Users/wjm/repos/dao-module/node_modules/@ethersproject/providers/src.ts/json-rpc-provider.ts:463:20)
    at step (/Users/wjm/repos/dao-module/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:46:23)
    at Object.throw (/Users/wjm/repos/dao-module/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:27:53)
    at rejected (/Users/wjm/repos/dao-module/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:19:65)
    at processTicksAndRejections (node:internal/process/task_queues:94:5) {
  reason: 'cannot estimate gas; transaction may fail or may require manual gas limit',
  code: 'UNPREDICTABLE_GAS_LIMIT',
  error: ProviderError: execution reverted: Previous transaction not executed yet
      at HttpProvider.request (/Users/wjm/repos/dao-module/node_modules/hardhat/src/internal/core/providers/http.ts:46:19)
      at HDWalletProvider.request (/Users/wjm/repos/dao-module/node_modules/hardhat/src/internal/core/providers/accounts.ts:131:34)
      at processTicksAndRejections (node:internal/process/task_queues:94:5)
      at EthersProviderWrapper.send (/Users/wjm/repos/dao-module/node_modules/@nomiclabs/hardhat-ethers/src/ethers-provider-wrapper.ts:13:20),
  method: 'estimateGas',
  transaction: {
    from: '0x140E42Ff76591Bf20675952Cc1B15774F75707c0',
    to: '0xD0A9A4cd312E046642341b70221358095C9c0cCE',
    data: '0x14604b8c00000000000000000000000000000000000000000000000000000000000000e00000000000000000000000000000000000000000000000000000000000000140000000000000000000000000140e42ff76591bf20675952cc1b15774f75707c0000000000000000000000000000000000000000000000000000000000000008c00000000000000000000000000000000000000000000000000000000000001a000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000002b6a785750356766764f5a6632444e74677375445a4f61726d35533772364b5762775255476456343367587300000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000029205dd2c5d9898f9a6c4c594fa5aa32c5931f9735207f9dcfaf6809bfd7e829b8196fff0c5cb9ec78aaf5049f82b6dc7c127e9c53a5629a53ff79f2de60ebb830000000000000000000000000000000000000000000000000000000000000000'
  }
}
```

## `proposal_8`
```
$ /Users/wjm/repos/dao-module/node_modules/.bin/hardhat --network rinkeby showProposal --module 0xD0A9A4cd312E046642341b70221358095C9c0cCE --proposal-file bridge_proposal_8.json
### Proposal ####
ID: vXkbEk0dEMrUpC3X6G48y1MVyuAPfMWxBbZAZjoW62Q
Transactions hashes hash: 0x51f17bd7dda62216f64845fffe9cd4e8501237f225dd349a84a73c93c4184ab5
Transactions hashes: [
  '0xa48556b0a3cb8246bf101355e3cc9059dbf6e81bb0635cce6e1cbd01b70ff3a5',
  '0x18f1d7351e938880ed67dee99ea1fb31937820d73cd312723661a712bd8220bc'
]
Transactions: [
  {
    to: '0x140E42Ff76591Bf20675952Cc1B15774F75707c0',
    value: '102',
    data: '0x',
    operation: 0
  },
  {
    to: '0x9AD2Bc9435D41Cc6f55a681552071C2EabDB2b31',
    value: '902',
    data: '0x',
    operation: 0
  }
]
✨  Done in 4.38s.

$ /Users/wjm/repos/dao-module/node_modules/.bin/hardhat --network rinkeby addProposal --module 0xD0A9A4cd312E046642341b70221358095C9c0cCE --proposal-file bridge_proposal_8.json
Transaction: 0x0ff19a69d318b3e103ada068047215560d912858ed9bcd220d8f62802b7c8b7c
✨  Done in 7.55s.

$ /Users/wjm/repos/dao-module/node_modules/.bin/hardhat --network rinkeby executeProposal --module 0xD0A9A4cd312E046642341b70221358095C9c0cCE --proposal-file bridge_proposal_8.json
Transaction: 0xe269b04475c6265fe1ebcbe35ae123bac53e652ae5dee9e511bcba989a8b68f8
An unexpected error occurred:

Error: cannot estimate gas; transaction may fail or may require manual gas limit (error={"name":"ProviderError","code":3,"data":"0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002550726576696f7573207472616e73616374696f6e206e6f7420657865637574656420796574000000000000000000000000000000000000000000000000000000"}, method="estimateGas", transaction={"from":"0x140E42Ff76591Bf20675952Cc1B15774F75707c0","to":"0xD0A9A4cd312E046642341b70221358095C9c0cCE","data":"0x14604b8c00000000000000000000000000000000000000000000000000000000000000e000000000000000000000000000000000000000000000000000000000000001400000000000000000000000009ad2bc9435d41cc6f55a681552071c2eabdb2b31000000000000000000000000000000000000000000000000000000000000038600000000000000000000000000000000000000000000000000000000000001a000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000002b76586b62456b3064454d7255704333583647343879314d5679754150664d577842625a415a6a6f573632510000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002a48556b0a3cb8246bf101355e3cc9059dbf6e81bb0635cce6e1cbd01b70ff3a518f1d7351e938880ed67dee99ea1fb31937820d73cd312723661a712bd8220bc0000000000000000000000000000000000000000000000000000000000000000"}, code=UNPREDICTABLE_GAS_LIMIT, version=providers/5.0.23)
    at Logger.makeError (/Users/wjm/repos/dao-module/node_modules/@ethersproject/logger/src.ts/index.ts:205:28)
    at Logger.throwError (/Users/wjm/repos/dao-module/node_modules/@ethersproject/logger/src.ts/index.ts:217:20)
    at checkError (/Users/wjm/repos/dao-module/node_modules/@ethersproject/providers/src.ts/json-rpc-provider.ts:68:16)
    at EthersProviderWrapper.<anonymous> (/Users/wjm/repos/dao-module/node_modules/@ethersproject/providers/src.ts/json-rpc-provider.ts:463:20)
    at step (/Users/wjm/repos/dao-module/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:46:23)
    at Object.throw (/Users/wjm/repos/dao-module/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:27:53)
    at rejected (/Users/wjm/repos/dao-module/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:19:65)
    at processTicksAndRejections (node:internal/process/task_queues:94:5) {
  reason: 'cannot estimate gas; transaction may fail or may require manual gas limit',
  code: 'UNPREDICTABLE_GAS_LIMIT',
  error: ProviderError: execution reverted: Previous transaction not executed yet
      at HttpProvider.request (/Users/wjm/repos/dao-module/node_modules/hardhat/src/internal/core/providers/http.ts:46:19)
      at HDWalletProvider.request (/Users/wjm/repos/dao-module/node_modules/hardhat/src/internal/core/providers/accounts.ts:131:34)
      at processTicksAndRejections (node:internal/process/task_queues:94:5)
      at EthersProviderWrapper.send (/Users/wjm/repos/dao-module/node_modules/@nomiclabs/hardhat-ethers/src/ethers-provider-wrapper.ts:13:20),
  method: 'estimateGas',
  transaction: {
    from: '0x140E42Ff76591Bf20675952Cc1B15774F75707c0',
    to: '0xD0A9A4cd312E046642341b70221358095C9c0cCE',
    data: '0x14604b8c00000000000000000000000000000000000000000000000000000000000000e000000000000000000000000000000000000000000000000000000000000001400000000000000000000000009ad2bc9435d41cc6f55a681552071c2eabdb2b31000000000000000000000000000000000000000000000000000000000000038600000000000000000000000000000000000000000000000000000000000001a000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000002b76586b62456b3064454d7255704333583647343879314d5679754150664d577842625a415a6a6f573632510000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002a48556b0a3cb8246bf101355e3cc9059dbf6e81bb0635cce6e1cbd01b70ff3a518f1d7351e938880ed67dee99ea1fb31937820d73cd312723661a712bd8220bc0000000000000000000000000000000000000000000000000000000000000000'
  }
}
```

**Comment by auryn-macmillan** [comment]
Closing because this appears to be stale. Feel free to reopen if it's still an issue.
